// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatching.Database;

#nullable disable

namespace MovieWatching.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250310223815_AddRelationshipMovieSessionPlan")]
    partial class AddRelationshipMovieSessionPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("MovieWatching.Database.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AddedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieSessionPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("When")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieSessionPlanId")
                        .IsUnique();

                    b.ToTable("MovieSessions");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieSessionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("MovieSessionPlans");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieSessionPlanId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("VoterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("VoterId");

                    b.HasIndex("MovieSessionPlanId", "MovieId", "VoterId")
                        .IsUnique();

                    b.ToTable("MovieVotes");
                });

            modelBuilder.Entity("MovieWatching.Database.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieWatching.Database.UserOrganizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserOrganizers");
                });

            modelBuilder.Entity("MovieWatching.Database.Movie", b =>
                {
                    b.HasOne("MovieWatching.Database.User", "AddedBy")
                        .WithMany("Movies")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieSession", b =>
                {
                    b.HasOne("MovieWatching.Database.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWatching.Database.MovieSessionPlan", "MovieSessionPlan")
                        .WithOne("Session")
                        .HasForeignKey("MovieWatching.Database.MovieSession", "MovieSessionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieSessionPlan");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieSessionPlan", b =>
                {
                    b.HasOne("MovieWatching.Database.UserOrganizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieVote", b =>
                {
                    b.HasOne("MovieWatching.Database.Movie", "Movie")
                        .WithMany("Votes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWatching.Database.MovieSessionPlan", "MovieSessionPlan")
                        .WithMany("Votes")
                        .HasForeignKey("MovieSessionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWatching.Database.User", "Voter")
                        .WithMany("Votes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieSessionPlan");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("MovieWatching.Database.UserOrganizer", b =>
                {
                    b.HasOne("MovieWatching.Database.User", "User")
                        .WithOne("Organizer")
                        .HasForeignKey("MovieWatching.Database.UserOrganizer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWatching.Database.Movie", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MovieWatching.Database.MovieSessionPlan", b =>
                {
                    b.Navigation("Session");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MovieWatching.Database.User", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Organizer");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
